### PR TITLE
Update kv.py

### PR DESCRIPTION
**Pull request by addyess**
import `MutableMapping` correctly for python3

### CODE REVIEW

**Comment by addyess** [comment]
@mgax what's the chances in 2022 of a `0.4` release?

**Comment by mgax** [comment]
@addyess TBH I wasn't aware that anybody was using this package. https://github.com/mgax/kv/issues/2#issuecomment-344631609 applies just as well 5 years later 😆

Would a release of the current `master` to PyPI, tagged with version `0.4`, be helpful? Is something that would make sense to fix before making a release?

**Comment by addyess** [comment]
> @addyess TBH I wasn't aware that anybody was using this package. https://github.com/mgax/kv/issues/2#issuecomment-344631609 applies just as well 5 years later 😆
> 
> Would a release of the current `master` to PyPI, tagged with version `0.4`, be helpful? Is something that would make sense to fix before making a release?

If you did publish an 0.4 release to pypi, I wouldn't protest. I'd be back in the office in a few days to try it out.

**Comment by mgax** [comment]
> If you did publish an 0.4 release to pypi, I wouldn't protest. I'd be back in the office in a few days to try it out.

@addyess I've published version 0.4: https://pypi.org/project/kv/0.4/. The project now has a CI, and requires Python 3.8 or above. I hope that doesn't break anything for you!

**Pull request merged**
